graph LR
1:startevent:((startevent)) --> 2:task:(Check defect and calculate repair cost)
2:task:(Check defect and calculate repair cost) --> 3:exclusivegateway:{x}
3:exclusivegateway:{x} --> |Costs are acceptable| 4:parallelgateway:{AND}
3:exclusivegateway:{x} --> |Costs are not acceptable| 9:endevent:((endevent))
4:parallelgateway:{AND} --> 5:task:(Check and repair hardware)
4:parallelgateway:{AND} --> 6:task:(Check and configure software)
5:task:(Check and repair hardware) --> 7:exclusivegateway:{x}
6:task:(Check and configure software) --> 8:exclusivegateway:{x}
7:exclusivegateway:{x} --> |No error detected| 10:endevent:((endevent))
7:exclusivegateway:{x} --> |Error detected| 5:task:(Check and repair hardware)
8:exclusivegateway:{x} --> |No error detected| 10:endevent:((endevent))
8:exclusivegateway:{x} --> |Error detected| 6:task:(Check and configure software)

