graph LR
1:startevent:((startevent)) --> 2:task:(Employee Submits Vacation Request)
2:task:(Employee Submits Vacation Request) --> 3:task:(Supervisor Receives Request)
3:task:(Supervisor Receives Request) --> 4:exclusivegateway:{x}
4:exclusivegateway:{x} --> |Request Approved| 5:task:(Notification to HR)
4:exclusivegateway:{x} --> |Request Rejected| 6:task:(Return Application to Employee)
5:task:(Notification to HR) --> 7:task:(HR Completes Management Procedures)
7:task:(HR Completes Management Procedures) --> 8:endevent:((endevent))
6:task:(Return Application to Employee) --> 8:endevent:((endevent))

